//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_A_Lot_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eft
    {
        public int ID { get; set; }
        public int paymentID { get; set; }
        public string AccHolder { get; set; }
        public string Bank { get; set; }
        public string AccNo { get; set; }
        public string Branch { get; set; }
    
        public virtual payment payment { get; set; }
    }
}
