//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_A_Lot_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int itemlist { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Tblorder Tblorder { get; set; }
        public virtual Tblproduct Tblproduct { get; set; }
    }
}
