//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_A_Lot_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblcart
    {
        public int cartID { get; set; }
        public int customerID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
    
        public virtual Tblcustomer Tblcustomer { get; set; }
        public virtual Tblproduct Tblproduct { get; set; }
    }
}
