//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_A_Lot_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchedule
    {
        public int scheduleID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Sname { get; set; }
        public string Cname { get; set; }
        public string contacts { get; set; }
        public string discription { get; set; }
        public Nullable<int> quantity { get; set; }
        public string date { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
